name: Tag and publish
on:
  push:
    branches:
      - main
jobs:
  tag:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: "main"
        fetch-depth: 0
        token: ${{ secrets.SERVICE_TOKEN }}
    - name: Compute new version number
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.SERVICE_TOKEN }}
        release_branches: "main"
        default_bump: patch
        dry_run: false
  publish:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: '1.14.12'
      GO_OS: 'linux'
      GO_ARCH: 'amd64'
      SINGULARITY_VERSION: '3.7.0'
    needs: tag
    steps:
      - uses: actions/checkout@v4
      - name: Pull latest changes
        run: git pull origin main
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          build-essential \
          libssl-dev \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          wget \
          pkg-config \
          procps
      - name: Install GO
        run: |
          wget https://dl.google.com/go/go$GO_VERSION.$GO_OS-$GO_ARCH.tar.gz
          sudo tar -C /usr/local -xzvf go$GO_VERSION.$GO_OS-$GO_ARCH.tar.gz
          sudo rm go$GO_VERSION.$GO_OS-$GO_ARCH.tar.gz
          echo 'export PATH=$PATH:/usr/local/go/bin' | sudo tee -a /etc/profile
      - name: Install Singularity
        run: |
          cd ..
          wget https://github.com/hpcng/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz
          sudo tar -xzf singularity-${SINGULARITY_VERSION}.tar.gz
          sudo rm singularity-${SINGULARITY_VERSION}.tar.gz
          echo "Finished installing binaries"
          export PATH=$PATH:/usr/local/go/bin
          cd singularity
          sudo ./mconfig --without-suid
          sudo make -C ./builddir
          sudo make -C ./builddir install
      - name: Build sif container
        run: |
          ls /
          ls
          mkdir build
          sudo singularity build build/container.sif scripts/singularity_build.def
      - name: Login and Deploy Container
        run: |
          latest_tag=$(git ls-remote --tags --refs --sort="v:refname" | tail -n1 | sed 's/.*\/v//')
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ github.actor }} --password-stdin oras://ghcr.io
          singularity push build/container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:$latest_tag
          singularity push build/container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:latest
